### PR TITLE
API-1783: bump(k8s): update k8s to 1.30

### PR DESCRIPTION
**Pull request by dinhxuanvu**
1. Bump k8s to v1.30.0
2. Fix deepcopy-gen script

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
Note: openshift components haven't been bumped yet. Will do when those components have been updated (via pending PRs).

**Comment by dinhxuanvu** [comment]
Updated to 1.30.0-rc.0

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
