### PR TITLE
Migrate to go.mod and kubernetes 1.17.0

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@deads2k we need `replace` here to compete with kubernetes/kubernetes go.mod that use staging... replace will override the staging repos.

**Comment by mfojtik** [comment]
the job is being removed in https://github.com/openshift/release/pull/6459 (thanks @soltysh)

**Comment by soltysh** [comment]
Adding approve manually, b/c bot doesn't want to do it and @mfojtik is in the approvers for this repo.

**Comment by soltysh** [comment]
Removing the approved based on explicit ask from @mfojtik

**Pull request merged**
